import type { NextConfig } from "next"

const isProduction = process.env.NODE_ENV === "production"

// Every brand icon in public/ (generated by `npm run brand:icons`); their names aren't fingerprinted,
// so they're cached for a week and revalidated in the background rather than forever
const BRAND_ASSETS =
  "/:asset(favicon\\.ico|favicon(?:-\\d+x\\d+)?\\.png|apple-touch-icon(?:-\\d+x\\d+)?\\.png|icon-\\d+x\\d+\\.png|maskable-icon(?:-\\d+x\\d+)?\\.png|monochrome-icon\\.png|safari-pinned-tab\\.svg|linkpilot-mark\\.(?:png|svg))"

const SECURITY_HEADERS = [
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=(), browsing-topics=()" },
  // No other site may frame the app (clickjacking)
  { key: "X-Frame-Options", value: "DENY" },
  { key: "Content-Security-Policy", value: "frame-ancestors 'none'" },
  // HTTPS only once deployed; on local http it would do nothing useful
  ...(isProduction ? [{ key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains" }] : []),
]

const nextConfig: NextConfig = {
  // No "X-Powered-By: Next.js" on responses
  poweredByHeader: false,
  // Files read from disk at runtime ship with the routes that read them: prompt templates and
  // dummy data for the API, the fonts and the logo for the social preview cards
  outputFileTracingIncludes: {
    "/api/**/*": ["./src/prompts/**/*", "./src/data/**/*"],
    "/og/**/*": ["./src/assets/fonts/**/*", "./public/icon-256x256.png"],
  },
  // The dev-only Next.js badge would sit on the sidebar's pinned Global AI Prompts item
  devIndicators: { position: "bottom-right" },
  async headers() {
    return [
      { source: "/:path*", headers: SECURITY_HEADERS },
      { source: BRAND_ASSETS, headers: [{ key: "Cache-Control", value: "public, max-age=604800, stale-while-revalidate=86400" }] },
    ]
  },
  // The manifest is app/manifest.ts (/manifest.webmanifest); tools that look for the other common names find it too
  async rewrites() {
    return [
      { source: "/manifest.json", destination: "/manifest.webmanifest" },
      { source: "/site.webmanifest", destination: "/manifest.webmanifest" },
    ]
  },
}

export default nextConfig;
