import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "outline-variant": "#bdc9c6",
        "primary-container": "#0f766e",
        "surface-container-highest": "#d9e3f6",
        "on-primary-container": "#a3faef",
        "on-tertiary-fixed": "#151c27",
        "on-secondary-fixed-variant": "#763300",
        primary: "#005c55",
        "on-secondary-container": "#682c00",
        "secondary-fixed-dim": "#ffb68e",
        "secondary-container": "#fd8a42",
        "tertiary-fixed-dim": "#c0c7d6",
        "on-surface-variant": "#3e4947",
        "on-tertiary-fixed-variant": "#404754",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#9cf2e8",
        outline: "#6e7977",
        "inverse-primary": "#80d5cb",
        "on-tertiary-container": "#e4ebfb",
        surface: "#f8f9ff",
        tertiary: "#4b525f",
        "surface-container-low": "#eff4ff",
        "on-primary": "#ffffff",
        "tertiary-container": "#636a78",
        "surface-container-high": "#dee9fc",
        "surface-container": "#e6eeff",
        background: "#FAF7F2",
        "inverse-surface": "#27313f",
        "surface-variant": "#d9e3f6",
        "surface-tint": "#006a63",
        "secondary-fixed": "#ffdbca",
        "primary-fixed-dim": "#80d5cb",
        "on-primary-fixed": "#00201d",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#dce2f3",
        "on-surface": "#121c2a",
        secondary: "#9b4500",
        "surface-dim": "#d0dbed",
        "on-background": "#121c2a",
        "surface-bright": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#00504a",
        "on-secondary-fixed": "#331200",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "stack-lg": "32px",
        "container-max": "1280px",
        "sidebar-width": "280px",
        "stack-sm": "8px",
        "stack-md": "16px",
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        code: ["var(--font-mono)", "monospace"],
      },
    },
  },
  plugins: [],
}
export default config
